# Header
menu:
  Home: /
  Archives: /archives
  About: /about
#rss: /atom.xml
github: https://github.com/maqduni
linkedin: https://www.linkedin.com/in/iskandar-rafiev-720b3a39/
stackoverflow: https://stackoverflow.com/users/5053866/maqduni

# Content
excerpt_link: Read More
fancybox: true
recent_posts_limits: 5

# Sidebar
sidebar: right
widgets:
- category
#- tag
- tagcloud
#- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
